server:
  port: 8030
spring:
  application:
    name: bookclient
  thymeleaf:
    profix: classpath:/templates/
    suffix: .html
eureka:
  instance:
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
