server:
  port: 8050
eureka:
  instance:
    prefer-ip-address: true
  clinet:
    service-url:
      defaultZone: http://localhost:8761/eureka/
spring:
  application:
    name: borrow
  datasource:
    name: library
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/library?useUnicode=true&charactreUncoding=utf-8
    username: root
    password: wsj666
mybatis:
  mapper-locations: classpath:/mapping/*.xml
  type-aliases-package: com.sj.entity